# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup ENV
      run: |
        touch .env
        echo SECRET_KEY=secret >> .env
        echo DB_HOST=db >> .env
        echo DB_NAME=conduit >> .env
        echo DB_USER=postgres >> .env
        echo DB_PASSWORD=abc >> .env
        cat .env
    - name: Start app
      run: docker-compose up --build
    - name: Run migrations
      run: docker-compose run api rake db:migrate
    - name: Run tests
      run: docker-compose run api rspec
